CREATE EXTENSION IF NOT EXISTS vector WITH SCHEMA public;

CREATE TABLE public.papers (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openalex_id TEXT NOT NULL UNIQUE CHECK (btrim(openalex_id) <> ''),
    doi TEXT,
    title TEXT NOT NULL CHECK (btrim(title) <> ''),
    abstract TEXT,
    publication_year INTEGER CHECK (publication_year BETWEEN 1 AND 2100),
    cited_by_count INTEGER NOT NULL DEFAULT 0 CHECK (cited_by_count >= 0),
    metadata JSONB CHECK (metadata IS NULL OR jsonb_typeof(metadata) = 'object'),
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE public.topics (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    openalex_id TEXT NOT NULL UNIQUE CHECK (btrim(openalex_id) <> ''),
    name TEXT NOT NULL CHECK (btrim(name) <> '')
);

CREATE TABLE public.paper_topics (
    paper_id BIGINT NOT NULL REFERENCES public.papers(id) ON DELETE CASCADE,
    topic_id BIGINT NOT NULL REFERENCES public.topics(id) ON DELETE CASCADE,
    score REAL NOT NULL CHECK (score BETWEEN 0 AND 1),
    PRIMARY KEY (paper_id, topic_id)
);

CREATE INDEX paper_topics_topic_id_idx ON public.paper_topics (topic_id);

CREATE TABLE public.citations (
    citing_paper_id BIGINT NOT NULL REFERENCES public.papers(id) ON DELETE CASCADE,
    cited_paper_id BIGINT NOT NULL REFERENCES public.papers(id) ON DELETE CASCADE,
    PRIMARY KEY (citing_paper_id, cited_paper_id),
    CHECK (citing_paper_id <> cited_paper_id)
);

CREATE INDEX citations_cited_paper_id_idx ON public.citations (cited_paper_id);
